### ISSUE TITLE
When playing skyblock my game ran really really bad and I thought maybe the server was just laggy. After investigating I figured out it was ChatTriggers mod. To verify I asked a friend if he was running really low frames and he was. I told him to take out ChatTriggers from his mods folder and his game ran buttery smooth. I'm not sure what the exact problem is but I can say with confidence there is something wrong with ChatTriggers. I have ran this mod for a while without any issues and today when I logged on at around noon eastern time, the game ran really bad. I hope this can help get the mod fixed since I REALLY enjoy using it and miss it a ton.

### ISSUE THREAD

**Issue by GordonPamsy** [ChatTriggers/ChatTriggers#203]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
 - ChatTriggers Version: [eg. 0.18.4]
 - Minecraft Version: [eg. 1.8.9]
- Java Version: [eg 1.8.0_231]

**Additional context**

**Comment by FalseHonesty** [comment]
Well, without you filling out any of the issue's body, it's quite unlikely the issue is actually due to the mod, rather, its likely due to one of the modules you have installed. Remove your modules one-by-one until your FPS returns to normal, and then you will have found the module causing the issue, and you can contact the creator of said module to see what they can do for you. I welcome you to join [our discord](https://discord.gg/chattriggers) in order to find the creator of the module causing issues.

**Comment by rune-lol** [comment]
@FalseHonesty my game runs fine with no chattriggers, bad with chattriggers and NO modules, and it runs unplayable with some modules ( i know this is the module devs fault )

**Comment by kerbybit** [comment]
a module specific issue should be brought up with the module creator. not much we can do about bad code
