### ISSUE TITLE
Add align options for Rectangle objects

### ISSUE THREAD

**Issue by camnwalter** [ChatTriggers/ChatTriggers#221]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd imagine it to be similar to the way Display and Text have their own .setAlign() method, but allowing to align the rectangle in the center or right and having the width and height adjusting accordingly.

**Describe alternatives you've considered**
Yes, I know you can make it so it subtracts half the width of what you're using to make it centered, but this just makes it nicer and since it is already implemented in Display and Text, I don't think it's too irrelevant to add.

**Additional context**
This would just be a nice QOL feature that I think people would use.

**Comment by camnwalter** [comment]
Adding onto this, if there was an option for aligning the x-axis and the y-axis separately that would be nice.

**Comment by FalseHonesty** [comment]
This doesn't really make sense to be in CT's standard library imo, the Rectangle class is just a simple wrapper around drawing a GL rect. This is implemented in Displays because each of their lines can have different widths, making right-alignment tricky. If you want easy behavior like this, look into a library like Elementa.
