### ISSUE TITLE
Random hangs still occur on ubuntu

### ISSUE THREAD

**Issue by TheScwumbler** [ChatTriggers/ChatTriggers#234]
The update in https://github.com/ChatTriggers/ChatTriggers/tree/01f2a38ca831a8f9954c920adc5b762c1d377b7c claims to remove random hangs from ubuntu. I tried to compile it with ./gradlew build and in the folder build -> libs there was the compiled version. I placed the compiled version into my mods folder and ran minecraft. When I ran the /f list command in hypixel, my game froze. Am I doing something wrong? Is build -> libs the wrong folder? There is no compiled .jar file on the releases page for this branch, so I have to compile it myself.

**Comment by FalseHonesty** [comment]
Well we haven't actually released 1.4.0 yet so that is why there is no jars available, but building from source should produce a working jar. The commit that actually fixes that bug is here https://github.com/ChatTriggers/ChatTriggers/commit/f440bd3519e77bf5c75ec9a58674dc2d3367ad45, did you build after this commit was made?

**Comment by TheScwumbler** [comment]
Because I commented on a bug report, I got an email notification saying that it was closed via a branch. I clicked the link to the branch and then clicked the view code button or whatever its labeled with and it took me to the page. The branch that was linked in the email is the one I linked in my previous comment. I will try the branch you just linked when I have the chance.

**Comment by TheScwumbler** [comment]
Oh using the other branch worked perfectly. Thanks!
