### ISSUE TITLE
Change how loading works

### ISSUE THREAD

**Issue by FalseHonesty** [ChatTriggers/ChatTriggers#67]
Currently, loading is done by taking all files in the top level of a folder inside of the "modules" folder, and making them one string. This string is then passed into the global nashorn script engine, along with all of the other modules. This means that if two modules have the same global variable or function name, there will be errors.

**Goals**

- Ability to declare top level variables with the same name in different modules.
- Keep the ability to make libraries or APIs by having global functions or variables.
- Add more robust support for Sentry when loading scripts/modules for better error reporting.
- Add support for nested folders to load for more organization.
- Support for disabling modules through module metadata file

**Comment by FalseHonesty** [comment]
Possibly could be done by declaring in the module `metadata.json` whether or not the entire module is global. In this case, then every method and top level variable would be available to all modules, global or not. 

Issues arise when thinking about how to have each module have its own trigger environment, for example, how would a trigger know what context to switch to when calling its callback method? A possible solution would be to require the module name when registering triggers, however, that would make registering less clean. A possible fix would be providing a JavaScript level API that would allow them to write code such as

```javascript
register("moduleName",
    [
        ["tick", "tickMethod"],
        ["step", "stepMethod"]
    ]
);
```

The issue with that then comes with how to configure each individual trigger. The easiest, but probably not cleanest solution would be to add the module name parameter to the end of the `register()` helper method.

**Comment by kerbybit** [comment]
Disabling and enabling of modules should be handled through the `metadata.json` file. This would allow me to add easy support for gui button(s) in the module gui for quick enabling and disabling of modules without moving around files. This extra value will be appended to the end of the json object as `true` by default when a module is imported.

This will require that all modules have a metadata file including personal modules so there would have to be a way to auto generate a metadata file and fill it with empty values. This could also potentially help people fill in their metadata file before uploading because then they at least have a skeleton to fill in instead of just guessing values or leaving it blank.

Added this to the list of goals in original post

**Comment by kerbybit** [comment]
Local scoping has been achieved with the 0.14 release and improved in the 0.15 release with the use of anonymous function object passed into the trigger registers. The script loader should still be cleaned up, but those changes solves this for what I wanted. If anyone still wants a more locally scoped module loading, re-open this issue with a description of how this could be done better.
